<script setup lang="ts">
const router = useRouter()
const startScan = () => { router.push('/scan') }
</script>

<template>
  <main>
    <header class="border-b border-neutral-200 bg-white"><div class="mx-auto flex max-w-6xl items-center justify-between px-6 py-5"><div class="flex items-center gap-3"><div class="grid h-9 w-9 place-items-center rounded-xl bg-neutral-950 text-sm font-bold text-white">H</div><div><p class="font-semibold leading-none">HomeLens</p><p class="mt-1 text-xs text-neutral-500">Confidence-aware home intelligence</p></div></div><UButton color="neutral" variant="ghost" to="/analysis">View demo</UButton></div></header>
    <section class="mx-auto grid min-h-[calc(100vh-80px)] max-w-6xl items-center gap-12 px-6 py-16 lg:grid-cols-[1.05fr_.95fr]">
      <div><UBadge color="neutral" variant="subtle">Prototype · Physical-world software</UBadge><h1 class="mt-6 max-w-3xl text-5xl font-semibold tracking-[-0.045em] text-neutral-950 md:text-6xl">Measure a room. <span class="text-neutral-400">Know what the software is unsure about.</span></h1><p class="mt-6 max-w-xl text-lg leading-8 text-neutral-600">HomeLens turns a room scan into editable measurements, confidence scores, and an explainable planning model. It is intentionally built around uncertainty instead of hiding it.</p><div class="mt-8 flex flex-wrap gap-3"><UButton size="xl" @click="startScan">Start room scan</UButton><UButton size="xl" color="neutral" variant="outline" to="/analysis">Open sample analysis</UButton></div><div class="mt-10 grid max-w-xl grid-cols-3 gap-6 border-t border-neutral-200 pt-6"><div><p class="text-2xl font-semibold">3D-ready</p><p class="mt-1 text-sm text-neutral-500">Geometry model</p></div><div><p class="text-2xl font-semibold">Explicit</p><p class="mt-1 text-sm text-neutral-500">Confidence states</p></div><div><p class="text-2xl font-semibold">Human</p><p class="mt-1 text-sm text-neutral-500">Manual verification</p></div></div></div>
      <div class="rounded-[2rem] border border-neutral-200 bg-white p-5 shadow-xl shadow-neutral-200/50"><div class="rounded-[1.5rem] bg-neutral-950 p-6 text-white"><div class="flex items-center justify-between"><div><p class="text-xs uppercase tracking-[0.18em] text-neutral-400">Live room model</p><p class="mt-1 text-xl font-medium">Living Room</p></div><UBadge color="success" variant="subtle">Scanning</UBadge></div><div class="relative mt-8 aspect-[4/3] overflow-hidden rounded-2xl border border-white/10 bg-neutral-900"><div class="absolute inset-8 border border-dashed border-white/20" /><div class="absolute left-[18%] top-[24%] h-[48%] w-[64%] skew-y-[-4deg] border border-white/60" /><div class="absolute left-[18%] top-[24%] h-2 w-2 rounded-full bg-white" /><div class="absolute right-[17%] top-[18%] rounded-full border border-white/20 bg-neutral-950/80 px-3 py-1 text-xs">14.2 ft · 94%</div><div class="absolute bottom-4 left-4 right-4 rounded-xl bg-white/10 p-3 backdrop-blur"><p class="text-xs text-neutral-400">System note</p><p class="mt-1 text-sm">Ceiling height needs manual verification.</p></div></div></div></div>
    </section>
  </main>
</template>
